---

- name: Copy Kubernetes metallb manifests
  include: "{{ ansible_macros_dir }}/template_copy.yml"
  with_items:
    - name: Add metallb manifests
      src : "{{ ansible_templates_dir }}/metallb"
      dest: "{{ kube_metallb_dir }}"

- name: Create Kubernetes metalb
  become: false
  command: "kubectl apply -f {{ kube_metallb_dir }}"
